### ISSUE TITLE
Doesn't install under Python 3.6.0

### ISSUE THREAD

**Issue by cpmpercussion** [lionheart/requests-cloudkit#1]
Hi, I couldn't get `requests-cloudkit` to install under Python 3.

```python
$ pip3 install requests-cloudkit
Collecting requests-cloudkit
  Using cached requests-cloudkit-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v3/7yxzprtn5cs4rjy2yj5lf67c0000gn/T/pip-build-zpmhjvdq/requests-cloudkit/setup.py", line 15, in <module>
        execfile("requests_cloudkit/metadata.py", metadata)
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/v3/7yxzprtn5cs4rjy2yj5lf67c0000gn/T/pip-build-zpmhjvdq/requests-cloudkit/
```

Well `execfile` doesn't exist in Python 3, but are there other things that would stop the requests-cloudkit from being installed?

**Comment by dlo** [comment]
Updated to use `runpy` instead of `execfile`. Not sure if it works in Python 3 but I may go through later this week to update if it doesn't. Cheers 🎉
